### ISSUE TITLE
Apt repositories (at least for ubuntu bionic) contain only latest version in 0.x branch.

### ISSUE THREAD

**Issue by mwijngaard** [digitalocean/do-agent#111]
Before opening an issue, make sure there is not a similar issue [already open](https://github.com/digitalocean/do-agent/issues)

## Describe the problem
Apt repositories (at least for ubuntu bionic) contain only latest version in 0.x branch, which is over 2 years old. 

## Steps to reproduce
Run recommended install method ubuntu Bionic:
`curl -L https://agent.digitalocean.com/install.sh | sudo bash`

## Expected behavior
Latests packages should be available

## System Information
Distribution and version:
Ubuntu Bionic 18.04.2 LTS

**Comment by Hoenn** [comment]
@mwijngaard , if you're looking to install the new agent (the code in this repo), the install instructions can be found here https://www.digitalocean.com/docs/monitoring/how-to/switch-agents/ . The new agent will eventually be made available through `agent.digitalocean.com/install.sh` but in the mean time check the docs if you'd like to opt in to using the new agent beta.
