### ISSUE TITLE
Include init scripts in source code for packaging

### ISSUE THREAD

**Issue by alzeih** [digitalocean/do-agent#12]
The provided rpm and deb packages include init scripts for the associated platform. Could these be included here?

I think it will make it easier for other distributions to package do-agent, and make it clear if these files are covered by the same license as the source.

**Comment by alzeih** [comment]
I've extracted the files I have found from the packages, and I can post them here (as a gist) if this would be agreeable.

**Comment by eRadical** [comment]
I would also like to make a file for systemd after the init one...

**Comment by cagedmantis** [comment]
We plan to add the init scripts to the repository. They should be considered to have the same license as the project.

**Comment by alzeih** [comment]
Here are the files I extracted from the .deb and .rpm:

https://gist.github.com/alzeih/517e32c29a10b59d66902be41582ff61

@eRadical these do contain a systemd service file
