### ISSUE TITLE
do-agent home directory in the wrong location

### ISSUE THREAD

**Issue by rmbleeker** [digitalocean/do-agent#124]
## Describe the problem
After installing the new DO Metrics Agent I noticed the service account was created with its home directory in **/home**

## Steps to reproduce
For me this was an upgrade from the old Metrics Agent so I followed the upgrade steps at https://www.digitalocean.com/docs/monitoring/how-to/switch-agents/. However when I noticed this issue I removed the new Metrics Agent and performed a clean installation:

- `sudo apt purge do-agent`
- `sudo deluser do-agent`
- `sudo rm /etc/apt/sources.list.d/digitalocean-agent.list`
- `curl -sSL https://insights.nyc3.cdn.digitaloceanspaces.com/install.sh | sudo bash`

After this: 
- `getent passwd do-agent `
```
do-agent:x:119:65534::/home/do-agent:/usr/sbin/nologin
```

## Expected behavior
Directories that save state data for a service do not belong in **/home**. Their preferred location is **/var/lib/<service name>** according to the [Filesystem Hierarchy Standard](http://www.pathname.com/fhs/pub/fhs-2.3.html#VARLIBVARIABLESTATEINFORMATION). Alternatively, if a service does not need to save any state information, setting it's home directory to **/nonexistent** is common practice at least on Debian derived distributions like Ubuntu.

## System Information
Distribution and version:
Ubuntu 18.04.2 LTS

### do-agent information:
- `/opt/digitalocean/bin/do-agent --version`:
```
do-agent (DigitalOcean Agent)

Version:     2.0.2
Revision:    08dc07b
Build Date:  Thu Mar  7 19:07:30 UTC 2019
Go Version:  go1.11.5
Website:     https://github.com/digitalocean/do-agent

Copyright (c) 2019 DigitalOcean, Inc. All rights reserved.

This work is licensed under the terms of the Apache 2.0 license.
For a copy, see <https://www.apache.org/licenses/LICENSE-2.0.html>.
```
- `apt-cache policy do-agent`:
```
do-agent:
  Installed: 2.0.2
  Candidate: 2.0.2
  Version table:
 *** 2.0.2 500
        500 https://repos.insights.digitalocean.com/apt/do-agent main/main amd64 Packages
        100 /var/lib/dpkg/status
     2.0.1 500
        500 https://repos.insights.digitalocean.com/apt/do-agent main/main amd64 Packages
     2.0.0 500
        500 https://repos.insights.digitalocean.com/apt/do-agent main/main amd64 Packages
     1.1.3 500
        500 https://repos.insights.digitalocean.com/apt/do-agent main/main amd64 Packages
```

**Comment by rmbleeker** [comment]
For now I've corrected this issue by stopping the service and changing it's home directory to **/var/lib/do-agent**

- `sudo systemctl stop do-agent.service`
- `sudo usermod -m -d /var/lib/do-agent do-agent`
- `sudo rmdir /home/do-agent`

**Comment by blockloop** [comment]
@rmbleeker to my knowledge do-agent does not store any state information to disk. The user [is created](https://github.com/digitalocean/do-agent/blob/72e51bb4e14de349d1e6d0d02fbc96325d5e5f9a/packaging/scripts/before_install.sh#L33) using `adduser --system` which, [according to the manpage](https://linux.die.net/man/8/adduser), does not create a home directory (docs quoted below). 

> Note that useradd will not create a home directory for such an user, regardless of the default setting in /etc/login.defs (CREATE_HOME). You have to specify the -m options if you want a home directory for a system account to be created.

I've run a few tests and It appears that some distros do not follow this setting and we need to add the `-M` flag.

**Comment by rmbleeker** [comment]
Today I learned there is a difference between `useradd` (the program which man page you link to, even though it's title is **adduser**) and the Debian program `adduser`. From it's [man page](https://www.systutorials.com/docs/linux/man/8-adduser/):

```
Add a system user

<snip>

A home directory is created by the same rules as for normal 
users. The new system user will have the shell /usr/sbin/nologin 
(unless overridden with the --shell option), and have logins 
disabled. Skeletal configuration files are not copied.   
```

Adduser is Debian specific tool that calls itself a friendlier front-end to lower level tools like useradd. In scripts you probably want to use `useradd` since it exists on Debian derived systems as well as other Linux distributions, making your script more portable. That said, this fix seems to do the trick nicely.

**Comment by blockloop** [comment]
We are indeed using `adduser` which is a perl script on most Debian and Debian-derived systems. However, RHEL systems have a symbolic link  `/usr/sbin/adduser -> /usr/sbin/useradd`.

**Comment by rmbleeker** [comment]
The issue is fixed now but I would still recommend switching to `useradd`, which is a lower level tool but should be available on all GNU/Linux systems and offer the exact same functionality everywhere, making your script deterministic.
