### ISSUE TITLE
Oracle Linux support

### ISSUE THREAD

**Issue by silazare** [digitalocean/do-agent#128]
## Describe the problem
Hello, 
please consider to add Oracle Linux 7 support for do-agent install script - https://insights.nyc3.cdn.digitaloceanspaces.com/install.sh.
Logic should be as for RHEL.

My workaround was to add "**ol**" in `${dist}` options list, this works.

## System Information
Oracle Linux Server 7.6

**Comment by blockloop** [comment]
@silazare we don't have any plans to officially support Oracle Linux, but your fix seems to work :)

**Comment by silazare** [comment]
@blockloop yes, it works ok. Thanks for the clarification!
