### ISSUE TITLE
[CloudLinux] This script does not support the OS/Distribution on this machine

### ISSUE THREAD

**Issue by danilowm** [digitalocean/do-agent#129]
## Describe the problem
This script does not support the OS/Distribution on this machine

## Steps to reproduce
I remove old metrics, using:
sudo yum remove do-agent

## System Information
16 GB Memory / 320 GB Disk / NYC3 - CentOS 7.5 x64 
WHM - cPanel

### do-agent information:

> curl -sSL https://insights.nyc3.cdn.digitaloceanspaces.com/install.sh | sudo bash
> Cleaning up old sources...OK
> Verifying machine compatability...OK
> Verifying compatability with script...
> This script does not support the OS/Distribution on this machine.
> If you feel that this is an error contact support@digitalocean.com
> or create an issue at https://github.com/digitalocean/do-agent/issues/new.

**Comment by blockloop** [comment]
@danilowm can you please provide the contents of the following files: `/etc/os-release` and `/etc/redhat-release`

**Comment by danilowm** [comment]
Sure!

`/etc/os-release`

NAME="CloudLinux"
VERSION="7.6 (Vladimir Lyakhov)"
ID="cloudlinux"
ID_LIKE="rhel fedora centos"
VERSION_ID="7.6"
PRETTY_NAME="CloudLinux 7.6 (Vladimir Lyakhov)"
ANSI_COLOR="0;31"
CPE_NAME="cpe:/o:cloudlinux:cloudlinux:7.6:GA:server"
HOME_URL="https://www.cloudlinux.com/"
BUG_REPORT_URL="https://www.cloudlinux.com/support"

`/etc/redhat-release`

CloudLinux release 5.6 (Vladimir Lyakhov)

**Comment by blockloop** [comment]
do-agent does not _officially_ [support](https://github.com/digitalocean/do-agent#overview) CloudLinux. You can however download the install.sh script and change [https://github.com/digitalocean/do-agent/blob/8d88bf39b7d690601be6634d7718f0967d366f63/scripts/install.sh#L40](this line) from `centos|fedora)` to `centos|fedora|cloudlinux)` and try again.

**Comment by danilowm** [comment]
@blockloop i had to edit [this line too](https://github.com/digitalocean/do-agent/blob/8d88bf39b7d690601be6634d7718f0967d366f63/scripts/install.sh#L111) to `debian|ubuntu|centos|fedora|cloudlinux)` and maybe works

> Installed:
>   do-agent.x86_64 0:2.1.3-1                                                                                             
> 
> Complete!

**Comment by danilowm** [comment]
I accessed dashboard now and metrics really changed, but the alert continues

see: 
![see](https://i.imgur.com/8IoiRiM.png)

it worked or not?

**Comment by Hoenn** [comment]
hey @danilowm , at this point it's probably better to open a [support ticket](https://cloudsupport.digitalocean.com/s/) as there is plenty more than the do-agent involved getting those graphs. Going to close this for now, as this is probably unrelated to the code in the repo.

**Comment by truls1502** [comment]
I have created a fix on the PR #211 for CloudLinux.
