### ISSUE TITLE
Silent installation failure with defunct apt repos

### ISSUE THREAD

**Issue by scott** [digitalocean/do-agent#131]
**_Please only create a Github issue for bugs related to the code itself. If you are 
experiencing an issue with sending metrics, display graphs, errors from the agent,
etc, please contact https://cloudsupport.digitalocean.com/s/ so we can provide support_**

Before opening an issue, make sure there is not a similar issue [already open](https://github.com/digitalocean/do-agent/issues)

## Describe the problem
Installation silently fails when there are defunct entries in sources.list

## Steps to reproduce
Uninstall do-agent.  Add a defunct repo to sources.list and try to install.  I ran into this with a packagecloud.io repo that no longer existed.

## Expected behavior
Should still install or at least produce an error message to remove old entries from sources.

## System Information
Distribution and version:
Ubuntu 14.04

### do-agent information:
None because it didn't install.

I was able to resolve by manually removing the old entries from `/etc/apt/sources.list` and `/etc/apt/sources.d/[offending repo].list`

**Comment by blockloop** [comment]
@scott which installation process did you use? Can you please provide the output of the script when it failed?

the [install script](https://github.com/digitalocean/do-agent/blob/8d88bf39b7d690601be6634d7718f0967d366f63/scripts/install.sh#L54) should ignore failures while trying to update apt repositories. If any relevant updates failed, the following line that installs dependencies should fail.

**Comment by scott** [comment]
```
deploy@app1:/etc/apt/sources.list.d$ curl -sSL https://insights.nyc3.cdn.digitaloceanspaces.com/install.sh | sudo bash
Cleaning up old sources...OK
Verifying machine compatability...OK
Verifying compatability with script...OK
Reading package lists... Done
Building dependency tree       
Reading state information... Done
E: Unable to locate package do-agent
Installing apt repository...
W: Failed to fetch https://packagecloud.io/contribsys/inspeqtor/ubuntu/dists/trusty/main/source/Sources  HttpError429

W: Failed to fetch https://packagecloud.io/contribsys/inspeqtor/ubuntu/dists/trusty/main/binary-amd64/Packages  HttpError429

W: Failed to fetch https://packagecloud.io/contribsys/inspeqtor/ubuntu/dists/trusty/main/binary-i386/Packages  HttpError429

E: Some index files failed to download. They have been ignored, or old ones used instead.
Installing gpg key...OK
W: Failed to fetch https://packagecloud.io/contribsys/inspeqtor/ubuntu/dists/trusty/main/source/Sources  HttpError429

W: Failed to fetch https://packagecloud.io/contribsys/inspeqtor/ubuntu/dists/trusty/main/binary-amd64/Packages  HttpError429

W: Failed to fetch https://packagecloud.io/contribsys/inspeqtor/ubuntu/dists/trusty/main/binary-i386/Packages  HttpError429

E: Some index files failed to download. They have been ignored, or old ones used instead.
```

**Comment by blockloop** [comment]
It looks like the following command failed on your machine. Could you try to run this manually and paste the output here?

```
apt-get update -o Dir::Etc::sourcelist="sources.list.d/digitalocean-agent.list"
```

**Comment by scott** [comment]
I actually already removed the offending packagecloud.io repo from sources.list and got the new DO agent installed, so I can't really test that anymore.  I can still run it if you want, but I am not sure how much value it will provide.

**Comment by kyranb** [comment]
Running `apt-get update -o Dir::Etc::sourcelist="sources.list.d/digitalocean-agent.list"`

gives me

W: The repository 'http://ppa.launchpad.net/fkrull/deadsnakes-python2.7/ubuntu xenial Release' does not have a Release file.
E: Failed to fetch http://ppa.launchpad.net/fkrull/deadsnakes-python2.7/ubuntu/dists/xenial/main/binary-amd64/Packages  404  Not Found
E: Some index files failed to download. They have been ignored, or old ones used instead.

**Comment by blockloop** [comment]
Hmm. What about:

```
apt-get update -o Dir::Etc::sourcelist="sources.list.d/digitalocean-agent.list" -o Dir::Etc::sourceparts="-" -o APT::Get::List-Cleanup="0"
```

**Comment by blockloop** [comment]
Okay I was able to reproduce the problem and fix it. I'll be pushing a fix shortly.

**Comment by PaulMesko** [comment]
For anyone still running into this, you can run
`sudo apt update`
Explicitly accept the changes, then just then the install script again:
`curl -sSL https://insights.nyc3.cdn.digitaloceanspaces.com/install.sh | sudo bash`

**Comment by louderthan10** [comment]
I'm getting hitting this exact issue also on Ubuntu 14.04 after trying to [upgrade the Metrics Agent](https://www.digitalocean.com/docs/monitoring/how-to/upgrade-legacy-agent/) (on two different droplets, but configured via Serverpilot).

When I rant the two commands on the upgrade guide I get this output: 

```
Cleaning up old sources...OK
Verifying machine compatability...OK
Verifying compatability with script...OK
Reading package lists... Done
Building dependency tree       
Reading state information... Done
E: Unable to locate package do-agent
Installing apt repository...
Installing gpg key...OK
W: Failed to fetch https://repos.insights.digitalocean.com/apt/do-agent/dists/main/main/binary-amd64/Packages  server certificate verification failed. CAfile: /etc/ssl/certs/ca-certificates.crt CRLfile: none

W: Failed to fetch https://repos.insights.digitalocean.com/apt/do-agent/dists/main/main/binary-i386/Packages  server certificate verification failed. CAfile: /etc/ssl/certs/ca-certificates.crt CRLfile: none

E: Some index files failed to download. They have been ignored, or old ones used instead.
serverpilot@lt10-production:~$ curl -sSL https://insights.nyc3.cdn.digitaloceanspaces.com/install.sh | sudo bash
Cleaning up old sources...OK
Verifying machine compatability...OK
Verifying compatability with script...OK
Reading package lists... Done
Building dependency tree       
Reading state information... Done
E: Unable to locate package do-agent
Installing apt repository...
Installing gpg key...OK
W: Failed to fetch https://repos.insights.digitalocean.com/apt/do-agent/dists/main/main/binary-amd64/Packages  server certificate verification failed. CAfile: /etc/ssl/certs/ca-certificates.crt CRLfile: none

W: Failed to fetch https://repos.insights.digitalocean.com/apt/do-agent/dists/main/main/binary-i386/Packages  server certificate verification failed. CAfile: /etc/ssl/certs/ca-certificates.crt CRLfile: none

E: Some index files failed to download. They have been ignored, or old ones used instead.
```

Then after finding this page I ran: `sudo apt update`

Then ran: `apt-get update -o Dir::Etc::sourcelist="sources.list.d/digitalocean-agent.list" -o Dir::Etc::sourceparts="-" -o APT::Get::List-Cleanup="0"`

Gives me: 

```
Ign https://repos.insights.digitalocean.com main InRelease
Ign https://repos.insights.digitalocean.com main Release.gpg
Ign https://repos.insights.digitalocean.com main Release
Err https://repos.insights.digitalocean.com main/main amd64 Packages
  server certificate verification failed. CAfile: /etc/ssl/certs/ca-certificates.crt CRLfile: none
Err https://repos.insights.digitalocean.com main/main i386 Packages
  server certificate verification failed. CAfile: /etc/ssl/certs/ca-certificates.crt CRLfile: none
Ign https://repos.insights.digitalocean.com main/main Translation-en_US
Ign https://repos.insights.digitalocean.com main/main Translation-en
N: Ignoring file '20auto-upgrades.ucf-dist' in directory '/etc/apt/apt.conf.d/' as it has an invalid filename extension
W: Failed to fetch https://repos.insights.digitalocean.com/apt/do-agent/dists/main/main/binary-amd64/Packages  server certificate verification failed. CAfile: /etc/ssl/certs/ca-certificates.crt CRLfile: none

W: Failed to fetch https://repos.insights.digitalocean.com/apt/do-agent/dists/main/main/binary-i386/Packages  server certificate verification failed. CAfile: /etc/ssl/certs/ca-certificates.crt CRLfile: none

E: Some index files failed to download. They have been ignored, or old ones used instead.
```

**Comment by toxaq** [comment]
Likewise:

    Ign https://repos.insights.digitalocean.com main InRelease                     
    Ign https://repos.insights.digitalocean.com main Release.gpg                   
    Ign https://repos.insights.digitalocean.com main Release                       
    Err https://repos.insights.digitalocean.com main/main i386 Packages            
      server certificate verification failed. CAfile: /etc/ssl/certs/ca-certificates.crt CRLfile: none
    Ign https://repos.insights.digitalocean.com main/main Translation-en_US
    Ign https://repos.insights.digitalocean.com main/main Translation-en
    W: Failed to fetch https://repos.insights.digitalocean.com/apt/do-agent/dists/main/main/binary-    i386/Packages  server certificate verification failed. CAfile: /etc/ssl/certs/ca-certificates.crt CRLfile:     none
    
    E: Some index files failed to download. They have been ignored, or old ones used instead.


sudo apt update can't complete.

**Comment by thucnc** [comment]
Please support this issue ASAP, I got the same issue on production

**Comment by bsnyder788** [comment]
You should be able to workaround this issue by using HTTP for the APT repo instead of HTTPS. Below are commands to update the sources file appropriately. There will most likely not be an official change to the agent to use http for APT for Ubuntu 14.04 since it has reached EOL.

```
sed -i 's/https/http/g' /etc/apt/sources.list.d/digitalocean-agent.list
sudo apt-get update
sudo apt-get install do-agent
```
Please let me know if this does not work for you (or if you are seeing this error on a distro other than Ubuntu 14.04)

**Comment by louderthan10** [comment]
@bsnyder788's workaround worked for me. Thank you!

**Comment by FernandoGarcia** [comment]
Hi! 

@blockloop I have the same problem.

```
$ apt-get update -o Dir::Etc::sourcelist="sources.list.d/digitalocean-agent.list" -o Dir::Etc::sourceparts="-" -o APT::Get::List-Cleanup="0"
Ign https://repos.insights.digitalocean.com main InRelease
Ign https://repos.insights.digitalocean.com main Release.gpg
Ign https://repos.insights.digitalocean.com main Release
Err https://repos.insights.digitalocean.com main/main i386 Packages
  server certificate verification failed. CAfile: /etc/ssl/certs/ca-certificates.crt CRLfile: none
Ign https://repos.insights.digitalocean.com main/main Translation-en_US
Ign https://repos.insights.digitalocean.com main/main Translation-en
W: Failed to fetch https://repos.insights.digitalocean.com/apt/do-agent/dists/main/main/binary-i386/Packages  server certificate verification failed. CAfile: /etc/ssl/certs/ca-certificates.crt CRLfile: none

E: Some index files failed to download. They have been ignored, or old ones used instead.
```

```
$ wget -qO- https://insights.nyc3.cdn.digitaloceanspaces.com/install.sh | sudo bash
Cleaning up old sources...OK
Verifying machine compatability...OK
Verifying compatability with script...OK
Reading package lists... Done
Building dependency tree
Reading state information... Done
E: Unable to locate package do-agent
Installing apt repository...
Installing gpg key...OK
W: Failed to fetch https://repos.insights.digitalocean.com/apt/do-agent/dists/main/main/binary-i386/Packages  server certificate verification failed. CAfile: /etc/ssl/certs/ca-certificates.crt CRLfile: none

E: Some index files failed to download. They have been ignored, or old ones used instead.
```

Best regards.

**Comment by lucafas** [comment]
Hi I was found the same issue on `Ubuntu 14.04` after trying to upgrade the Metrics Agent.

## Problem:
```
$ curl -sSL https://insights.nyc3.cdn.digitaloceanspaces.com/install.sh | sudo bash
Cleaning up old sources...OK
Verifying machine compatability...OK
Verifying compatability with script...OK
Reading package lists... Done
Building dependency tree
Reading state information... Done
E: Unable to locate package do-agent
Installing apt repository...
Installing gpg key...OK
W: Failed to fetch https://repos.insights.digitalocean.com/apt/do-agent/dists/main/main/binary-amd64/Packages  server certificate verification failed. CAfile: /etc/ssl/certs/ca-certificates.crt CRLfile: none

W: Failed to fetch https://repos.insights.digitalocean.com/apt/do-agent/dists/main/main/binary-i386/Packages  server certificate verification failed. CAfile: /etc/ssl/certs/ca-certificates.crt CRLfile: none

E: Some index files failed to download. They have been ignored, or old ones used instead.
```


I inspected the install.sh script and i was able reproduce the problem sending the command at line 59:

```
apt-get -qq update -o Dir::Etc::sourcelist="sources.list.d/digitalocean-agent.list"
```
The response was:
```
W: Failed to fetch https://repos.insights.digitalocean.com/apt/do-agent/dists/main/main/binary-amd64/Packages  server certificate verification failed. CAfile: /etc/ssl/certs/ca-certificates.crt CRLfile: none

W: Failed to fetch https://repos.insights.digitalocean.com/apt/do-agent/dists/main/main/binary-i386/Packages  server certificate verification failed. CAfile: /etc/ssl/certs/ca-certificates.crt CRLfile: none

E: Some index files failed to download. They have been ignored, or old ones used instead.
```
## Solution:

I fixed my problem, dowloading the .sh script and replacing the `https` with `http` on `line 17` 
After launching another time the script, it worked for me.
I think it could be a temporary cert problem on the repo.


Below all the commands:
```
curl -L -o ./install.sh https://insights.nyc3.cdn.digitaloceanspaces.com/install.sh
sed -i '17s/https/http/' install.sh
chmod 775 install.sh 
./install.sh
```

I hope it can help someone

**Comment by muhdazrain** [comment]
> Hi I found the same issue on `Ubuntu 14.04` after trying to upgrade the Metrics Agent.
> 
> ## Problem:
> ```
> $ curl -sSL https://insights.nyc3.cdn.digitaloceanspaces.com/install.sh | sudo bash
> Cleaning up old sources...OK
> Verifying machine compatability...OK
> Verifying compatability with script...OK
> Reading package lists... Done
> Building dependency tree
> Reading state information... Done
> E: Unable to locate package do-agent
> Installing apt repository...
> Installing gpg key...OK
> W: Failed to fetch https://repos.insights.digitalocean.com/apt/do-agent/dists/main/main/binary-amd64/Packages  server certificate verification failed. CAfile: /etc/ssl/certs/ca-certificates.crt CRLfile: none
> 
> W: Failed to fetch https://repos.insights.digitalocean.com/apt/do-agent/dists/main/main/binary-i386/Packages  server certificate verification failed. CAfile: /etc/ssl/certs/ca-certificates.crt CRLfile: none
> 
> E: Some index files failed to download. They have been ignored, or old ones used instead.
> ```
> 
> I inspected the install.sh script and i was able reproduce the problem sending the command at line 59:
> 
> ```
> apt-get -qq update -o Dir::Etc::sourcelist="sources.list.d/digitalocean-agent.list"
> ```
> 
> The response was:
> 
> ```
> W: Failed to fetch https://repos.insights.digitalocean.com/apt/do-agent/dists/main/main/binary-amd64/Packages  server certificate verification failed. CAfile: /etc/ssl/certs/ca-certificates.crt CRLfile: none
> 
> W: Failed to fetch https://repos.insights.digitalocean.com/apt/do-agent/dists/main/main/binary-i386/Packages  server certificate verification failed. CAfile: /etc/ssl/certs/ca-certificates.crt CRLfile: none
> 
> E: Some index files failed to download. They have been ignored, or old ones used instead.
> ```
> 
> ## Solution:
> I fixed my problem, dowloading the .sh script and replacing the `https` with `http` on `line 17`
> After launching another time the script, it worked for me.
> I think it could be a temporary cert problem on the repo.
> 
> Below all the commands:
> 
> ```
> curl -L -o ./install.sh https://insights.nyc3.cdn.digitaloceanspaces.com/install.sh
> sed -i '17s/https/http/' install.sh
> chmod 775 install.sh 
> ./install.sh
> ```
> 
> I hope it can help someone

Works for me. Thanks.
