### ISSUE TITLE
Daily cron job is not silent

### ISSUE THREAD

**Issue by alvinhochun** [digitalocean/do-agent#132]
## Describe the problem

The daily cron job appears to not have silenced the output from yum and thus produce useless mail daily. The mail has content:

```
/etc/cron.daily/do-agent:

Loaded plugins: fastestmirror
Loading mirror speeds from cached hostfile
Metadata Cache Created
```

## Steps to reproduce

1. Install the new do-agent
2. Wait a day

## Expected behavior

No useless cron mail should be sent.

## System Information
Distribution and version: CentOS 7

### do-agent information:

```
# /opt/digitalocean/bin/do-agent --version

do-agent (DigitalOcean Agent)

Version:     2.1.3
Revision:    6712f22
Build Date:  Mon Apr  8 13:56:04 UTC 2019
Go Version:  go1.11.5
Website:     https://github.com/digitalocean/do-agent

Copyright (c) 2019 DigitalOcean, Inc. All rights reserved.

This work is licensed under the terms of the Apache 2.0 license.
For a copy, see <https://www.apache.org/licenses/LICENSE-2.0.html>.
# yum --cacheonly list do-agent
Loaded plugins: fastestmirror
Installed Packages
do-agent.x86_64                                       2.1.3-1                                        @digitalocean-agent
```

**Comment by blockloop** [comment]
I suppose we should pipe stdout to /dev/null to prevent this

**Comment by alvinhochun** [comment]
Is this line missing a `-q` flag?

https://github.com/digitalocean/do-agent/blob/71379dd427f2299d3c54374d1f45ea25e3afdb88/scripts/update.sh#L9

**Comment by fithive** [comment]
We're also affected by this, I have started seeing new nightly emails from this cron.

-q flag mentioned by @alvinhochun would be appreciated

**Comment by blockloop** [comment]
Yes, that update.sh script is located at `/opt/digitalocean/do-agent/scripts/update.sh` and it's executed by the cron.daily job. You can modify the update.sh script manually for now and we'll have an update soon.
