### ISSUE TITLE
Project RoadMap? Proposed Features?

### ISSUE THREAD

**Issue by Marak** [digitalocean/do-agent#14]
Hello!

I've been using the new `do-agent` for a few production DO instances and am generally happy with how it's working.

I'm curious, is there a project roadmap for `do-agent`? Is there a list of proposed or intended upcoming features?

**Comment by cagedmantis** [comment]
Hello @Marak 
We posted some information on the [DigitalOcean blog](https://www.digitalocean.com/company/blog/improved-graphs/)  which contains some future plans for the agent. That's probably about as much as we are willing to share at this point. Please feel free to submit any recommendations or desired functionality to our [User Voice](https://digitalocean.uservoice.com) site. 

I'm going to close this Issue. Thank you for your interest. Let us know how we can build a better project.

**Comment by xmudrii** [comment]
Hi @cagedmantis !
I'll use this issue for my questions as it's somewhat relevant. As project welcomes contributions, and I'm looking to contribute, what does need to be done? I know that suite of tools and probably plugins are next, but there is no information on what does need to be done. Also, there are no opened issues or PRs. If there is anything to do, I'll be more than glad to help. =)
