### ISSUE TITLE
upstart compatible vs. systemd & security of script installation

### ISSUE THREAD

**Issue by inspire22** [digitalocean/do-agent#142]
Is there a way to use the new do-agent with upstart? I'm not a fan of systemd.

Also the bash upgrade script is a bit sketchy to me, if anyone hacked your github account, they could compromise the production systems of anyone who ran the script that you are recommending.  Good sysadmins will read the script, but 50% of sysadmins are not good and 25% of the good ones wouldn't catch it if someone was sneaky enough.

**Comment by blockloop** [comment]
The script doesn't force systemd or upstart. If you have systemd installed then that's what it uses, otherwise it uses upstart. As you probably know, Linux cannot have more than one init system so the script works with whichever you have.

The update script is issuing an apt/yum upgrade. Even if, by some chance, someone were to gain access to our Github (which is a feat in and of itself). They would have no access to our internal networking, our deployment processes, our private keys used to sign the packages, or any of the other mechanisms (which I won't specify in the public domain) we use to distribute do-agent.

**Comment by blockloop** [comment]
@inspire22 does this address your concerns?

**Comment by inspire22** [comment]
Thanks so much for your reply, I especially liked the Raphael allusion :)

My reason for disliking script-based upgrades/installations is that there is a history of people hacking users sessionids then being able to make changes on their accounts.  For example https://arstechnica.com/information-technology/2017/03/someone-is-putting-lots-of-work-into-hacking-github-developers/ though I also remember a story from awhile back of a reward offered that someone managed to hack in, though I can't recall the details.

Even in a short install.sh script, there's plenty of ways to obfuscate something even in a short script like this that then download and runs a shell script to pown a host.  But I know there are other projects that do this, and no-one else is raising red flags that I've heard of and most of the other admins probably know more than me.

I do see that the actual script doesn't run from github, but from assets.digitalocean.com, so perhaps that is more secure.  Thanks :)

**Comment by inspire22** [comment]
Regarding my problem with it not working on upstart systems, here's the error I'm getting:

`...
Creating /etc/systemd/system/do-agent.service...
Created symlink /etc/systemd/system/multi-user.target.wants/do-agent.service, pointing to /etc/systemd/system/do-agent.service.
Failed to start do-agent.service: Unknown unit: do-agent.service
See system logs and 'systemctl status do-agent.service' for details.
dpkg: error processing package do-agent (--configure):
 subprocess installed post-installation script returned error exit status 1
Errors were encountered while processing:
 do-agent
E: Sub-process /usr/bin/dpkg returned an error code (1)
root@bach:~# uname -a
Linux bach.nicepoem.com 4.4.0-112-generic #135-Ubuntu SMP Fri Jan 19 11:48:14 UTC 2018 i686 i686 i686 GNU/Linux`

It looks like it's trying to start a systemd service, any idea how to ask it to use upstart?

**Comment by blockloop** [comment]
Can you tell me the output you get when you run `which -a systemctl`

**Comment by blockloop** [comment]
if `which` command does not exist please use `command -v systemctl`

**Comment by inspire22** [comment]
root@bach:~# which -a systemctl
/bin/systemctl
root@bach:~# systemctl status do-agent.service
Failed to get properties: No such interface ''
root@bach:~# systemctl start do-agent
Failed to start do-agent.service: Unknown unit: do-agent.service
See system logs and 'systemctl status do-agent.service' for details.
root@bach:/var/log# ll /etc/systemd/system/do-agent.service
-rw-r--r-- 1 root root 371 Apr 30 15:04 /etc/systemd/system/do-agent.service

I believe i'm using upstart, so it makes sense the systemd service wouldn't be found by systemctl?
no entry in syslog
Thanks!

**Comment by blockloop** [comment]
@inspire22 the existence of `/bin/systemctl` on your machine means you are definitely not running upstart. Upstart and systemd are both Linux Init systems which cannot coexist. Ubuntu versions 15.05 and later run `systemd` by default. The installation script detects whether or not you're running systemd by checking for the `systemctl` binary. It installs the correct script based on your environment. The script that is bundled with the deb package is can be found [here](https://github.com/digitalocean/do-agent/blob/master/packaging/scripts/after_install.sh#L27). 

It seems like you are having another issue with the installation which is difficult to debug without the correct context. Unfortunately, I cannot gather that context here so I'll ask you to create a support ticket at https://cloudsupport.digitalocean.com/s/ so we can provide the appropriate support.
