### ISSUE TITLE
Method https has died unexpectedly!

### ISSUE THREAD

**Issue by sillycube** [digitalocean/do-agent#145]
**_Please only create a Github issue for bugs related to the code itself. If you are 
experiencing an issue with sending metrics, display graphs, errors from the agent,
etc, please contact https://cloudsupport.digitalocean.com/s/ so we can provide support_**

Before opening an issue, make sure there is not a similar issue [already open](https://github.com/digitalocean/do-agent/issues)

## Describe the problem
When I uninstalled do-agent and tried to upgrade to the latest version of do-agent, it gives "method https has died unexpectedly!"
## Steps to reproduce
just install it manually. 
Cleaning up old sources...OK
Verifying machine compatability...OK
Verifying compatability with script...OK
Reading package lists... Done
Building dependency tree
Reading state information... Done
Package 'do-agent' is not installed, so not removed
0 upgraded, 0 newly installed, 0 to remove and 275 not upgraded.
Installing apt repository...
E: Method https has died unexpectedly!
E: Sub-process https received signal 9.
Installing gpg key...OK
E: Method https has died unexpectedly!
E: Sub-process https received signal 9.

## System Information
Distribution and version:
Ubuntu 14.04

### do-agent information:
Paste the entire output

`/opt/digitalocean/bin/do-agent --version`:

_Ubuntu, Debian_

`apt-cache policy do-agent`:

_Fedora, CentOS_

`yum --cacheonly list do-agent`:

**Comment by blockloop** [comment]
Hey @sillycube this kind of error is usually related to an issue with apt or the package manager itself and not indicative of any issues with the package or the application. Please create a support ticket at https://cloudsupport.digitalocean.com/s/ so that you can receive the proper support.

**Comment by ivanovv** [comment]
@sillycube would be awesome if you could post the end result here!
