### ISSUE TITLE
Failed to install on ubuntu 16

### ISSUE THREAD

**Issue by belegnar** [digitalocean/do-agent#149]
## Describe the problem
Do-agent failed to install

## Steps to reproduce
$ curl -sSL https://insights.nyc3.cdn.digitaloceanspaces.com/install.sh | sudo bash
[sudo] password for ***: 
Cleaning up old sources...OK
Verifying machine compatability...OK
Verifying compatability with script...OK
Reading package lists... Done
Building dependency tree       
Reading state information... Done
E: Unable to locate package do-agent
Installing apt repository...
W: http://get.docker.io/ubuntu/dists/docker/Release.gpg: Signature by key 36A1D7869245C8950F966E92D8576A8BA88D21E9 uses weak digest algorithm (SHA1)
Installing gpg key...OK
W: http://get.docker.io/ubuntu/dists/docker/Release.gpg: Signature by key 36A1D7869245C8950F966E92D8576A8BA88D21E9 uses weak digest algorithm (SHA1)
Selecting previously unselected package do-agent.
(Reading database ... 100768 files and directories currently installed.)
Preparing to unpack .../do-agent_2.2.1_amd64.deb ...
Creating do-agent user...
Stopping systemctl service...
Unpacking do-agent (2.2.1) ...
Setting up do-agent (2.2.1) ...
Detecting SELinux
SELinux not enforced
Creating /etc/systemd/system/do-agent.service...
Created symlink /etc/systemd/system/multi-user.target.wants/do-agent.service, pointing to /etc/systemd/system/do-agent.service.
Failed to start do-agent.service: Unknown unit: do-agent.service
See system logs and 'systemctl status do-agent.service' for details.
dpkg: error processing package do-agent (--configure):
 subprocess installed post-installation script returned error exit status 1
Errors were encountered while processing:
 do-agentE: Sub-process /usr/bin/dpkg returned an error code (1)

## Expected behavior
do-agent installed and running

## System Information
# uname -a
Linux hhh 4.4.0-141-generic #167-Ubuntu SMP Wed Dec 5 10:40:15 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux
# lsb_release -a
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 16.04.5 LTS
Release:	16.04
Codename:	xenial

### do-agent information:
# ./do-agent --version

do-agent (DigitalOcean Agent)

Version:     2.2.1
Revision:    c79bf68
Build Date:  Tue May 14 16:20:41 UTC 2019
Go Version:  go1.12.1
Website:     https://github.com/digitalocean/do-agent

Copyright (c) 2019 DigitalOcean, Inc. All rights reserved.

This work is licensed under the terms of the Apache 2.0 license.
For a copy, see <https://www.apache.org/licenses/LICENSE-2.0.html>.

n# apt-cache policy do-agent
do-agent:
  Installed: 2.2.1
  Candidate: 2.2.1
  Version table:
 *** 2.2.1 500
        500 https://repos.insights.digitalocean.com/apt/do-agent main/main amd64 Packages
        100 /var/lib/dpkg/status
     2.2.0 500
        500 https://repos.insights.digitalocean.com/apt/do-agent main/main amd64 Packages
     2.1.3 500
        500 https://repos.insights.digitalocean.com/apt/do-agent main/main amd64 Packages
     2.0.2 500
        500 https://repos.insights.digitalocean.com/apt/do-agent main/main amd64 Packages
     2.0.1 500
        500 https://repos.insights.digitalocean.com/apt/do-agent main/main amd64 Packages
     2.0.0 500
        500 https://repos.insights.digitalocean.com/apt/do-agent main/main amd64 Packages
     1.1.3 500
        500 https://repos.insights.digitalocean.com/apt/do-agent main/main amd64 Packages

# systemctl list-unit-files | grep do-agent
do-agent.service                           enabled

**Comment by blockloop** [comment]
@belegnar I'm not sure what might have happened. We test all versions rigorously on [several versions](https://github.com/digitalocean/do-agent/blob/master/scripts/uat.sh#L24-L40) of the agent including 16.04. To be sure, I just created 5 16.04 droplets just now and installed the agent with curl and all were successful. 

Please reach out to https://cloudsupport.digitalocean.com/s/ to get support.
