### ISSUE TITLE
DEB repo

### ISSUE THREAD

**Issue by electropolis** [digitalocean/do-agent#16]
Is https://repos.sonar.digitalocean.com/apt main main avalaible? Because I get

`W: Failed to fetch https://repos.sonar.digitalocean.com/apt/dists/main/main/binary-amd64/Packages  Hash Sum mismatch`

**Comment by cagedmantis** [comment]
Hi @electropolis 
That may have been a momentary glitch. It's not really an issue with the agent code itself. If the problem persists please reach out to Digitalocean support and open a ticket with them.
