### ISSUE TITLE
Question: Does the DO Agent generate a log anywhere on the host system?

### ISSUE THREAD

**Issue by greg-alfaro** [digitalocean/do-agent#167]
## System Information
Distribution and version:
Debian Sid, do-agent v0.51, Do-Agent build HEAD.c799b1e

```>>> apt-cache policy do-agent
do-agent:
  Installed: 0.5.1
  Candidate: 0.5.1
  Version table:
 *** 0.5.1 500
        500 https://repos.sonar.digitalocean.com/apt main/main amd64 Packages
        100 /var/lib/dpkg/status```

**Comment by blockloop** [comment]
This version (0.5.1) of do-agent is no longer supported or maintained. Please [upgrade your agent to the latest version](https://www.digitalocean.com/docs/monitoring/how-to/upgrade-legacy-agent/).

That being said, the agent logs to stdout/stderr unless it's given the `--syslog` flag (which is used by default). You should be able to check the logs using `journalctl -u do-agent`
