### ISSUE TITLE
Agent shows wrong traffic

### ISSUE THREAD

**Issue by doom369** [digitalocean/do-agent#17]
Hello guys. Thanks for nice script. However after few hours of monitoring I found some inconsistencies between real droplet data and what agent show.

I have constant traffic for my droplet for ~1.0 Mbps in and out.

![low_traffic](https://cloud.githubusercontent.com/assets/1536494/22177316/f0d79844-e023-11e6-82ea-b7798a07b899.png)

Agent shows 0.07 Mbps in and 0.08 Mbps out. This is impossible. I also checked with `iftop`. Constant 1.0 Mbps with peaks to 6 Mbps but nothing of this is present on agent graphs.

Prev. graph was showing correct values.

**Comment by cagedmantis** [comment]
Hi @doom369 ,
Please open a ticket with [DigitalOcean support.](https://www.digitalocean.com/company/contact/). We will work with you to help fix this issue.
