### ISSUE TITLE
do-agent cron.daily script needs to be quieter.

### ISSUE THREAD

**Issue by agargiulo** [digitalocean/do-agent#175]
**_Please only create a Github issue for bugs related to the code itself. If you are 
experiencing an issue with sending metrics, display graphs, errors from the agent,
etc, please contact https://cloudsupport.digitalocean.com/s/ so we can provide support_**

Before opening an issue, make sure there is not a similar issue [already open](https://github.com/digitalocean/do-agent/issues)

## Describe the problem
Twice this week the agent updated in a `cron.daily` job and sent me an email with mostly junk from the output of the install script (or uninstall script, I can't tell)
#### Email Contents ####
```
/etc/cron.daily/do-agent:

nobody:x:99:
Detecting SELinux
setting nis_enabled to 1 to allow do-agent to execute
useradd: user 'do-agent' already exists
Creating /etc/systemd/system/do-agent.service...
removed ‘/etc/cron.daily/do-agent’
nobody:x:99:
Detecting SELinux
setting nis_enabled to 1 to allow do-agent to execute
useradd: user 'do-agent' already exists
Creating /etc/systemd/system/do-agent.service...
removed ‘/etc/cron.daily/do-agent’
```

## Steps to reproduce
With no updates available, the cron script works as intended.
When there's an update though, running the following produces messages from (un?)install scriptlets.
```bash
[10:20:49] % sudo yum -q -y update do-agent
nobody:x:99:
Detecting SELinux
setting nis_enabled to 1 to allow do-agent to execute
useradd: user 'do-agent' already exists
Creating /etc/systemd/system/do-agent.service...
removed ‘/etc/cron.daily/do-agent’
nobody:x:99:
Detecting SELinux
setting nis_enabled to 1 to allow do-agent to execute
useradd: user 'do-agent' already exists
Creating /etc/systemd/system/do-agent.service...
removed ‘/etc/cron.daily/do-agent’
sudo yum -q -y update do-agent  4.61s user 5.25s system 92% cpu 10.695 total
```

## Expected behavior
Given that the script was changed in #132 (e1b29ccce) to add the `-q -y` flags, I would expect this to not produce any output unless there was an error and none of the above looks like issues to me.

## System Information
Distribution and version:
```
[10:24:52] % cat /etc/centos-release
CentOS Linux release 7.6.1810 (Core)
```

### do-agent information:
Paste the entire output

`/opt/digitalocean/bin/do-agent --version`:
```
do-agent (DigitalOcean Agent)

Version:     3.2.1
Revision:    7647604
Build Date:  Mon Jun 24 14:47:42 UTC 2019
Go Version:  go1.12.1
Website:     https://github.com/digitalocean/do-agent

Copyright (c) 2019 DigitalOcean, Inc. All rights reserved.

This work is licensed under the terms of the Apache 2.0 license.
For a copy, see <https://www.apache.org/licenses/LICENSE-2.0.html>.
```

_Ubuntu, Debian_

`apt-cache policy do-agent`:

_Fedora, CentOS_

`yum --cacheonly list do-agent`:
```
Loaded plugins: changelog, etckeeper, fastestmirror, remove-with-leaves
Installed Packages
do-agent.x86_64                  3.2.1-1                   @digitalocean-agent
```

**Comment by bsnyder788** [comment]
This should be fixed with releases >= 3.3.1.
