### ISSUE TITLE
Protocol documentation?

### ISSUE THREAD

**Issue by kaithar** [digitalocean/do-agent#19]
To make this slightly more useful, is it possible to document the protocol used beyond it being gRPC, and ideally the exception the client has of the server side?  That would make it easier for both adding new metric collection and pointing it towards third party collection servers.

**Comment by mattkanwisher** [comment]
Yeah definitely we need to document this. Any applications you want to expand this for? I would love to hear your usecases.

 On a high level the metrics are the Prometheus  protocol featured here (https://docs.google.com/document/d/1ZjyKiKxZV83VI9ZKAXRGKaUKK2BIWCT7oiGBKDBpjEY/edit#heading=h.wnviarbnyxcj), its not grpc but protobufs over http . The auth is done with a header called X-Auth-Key.

**Comment by kaithar** [comment]
My primary use case is home brew monitoring on various bits of baremetal, this project feels like a good candidate for an environment agnostic monitoring agent.  If it's as happy monitoring minecraft server users or i2c connected ADCs as it is monitoring disk use then it makes for a very reusable project 👍
