### ISSUE TITLE
failed to read response body of sonar message: +invalid character

### ISSUE THREAD

**Issue by exodus4d** [digitalocean/do-agent#191]
## Describe the problem
The metric report seems to work. But there are some error reported in the `go-agent` logs:

```
/home/do-agent/cmd/do-agent/run.go:73: failed to send metrics: flush failure
/home/do-agent/pkg/clients/tsclient/client.go:465: failed to read response body of sonar message: +invalid character '<' looking for beginning of value
/home/do-agent/pkg/writer/sonar.go:68: failed to flush: received unexpected HTTP status: 503
```
## Steps to reproduce
watch err logs:
`journalctl -fp err`
... or service status:

![AtAydBR](https://user-images.githubusercontent.com/9299033/61589981-f33e0580-abb1-11e9-8093-46d1233407bf.png)

## System Information
Distribution and version:

### do-agent information:
```
do-agent (DigitalOcean Agent)

Version:     3.5.2
Revision:    a83fff5
Build Date:  Tue Jul 16 22:12:39 UTC 2019
Go Version:  go1.12.1
Website:     https://github.com/digitalocean/do-agent

Copyright (c) 2019 DigitalOcean, Inc. All rights reserved.

This work is licensed under the terms of the Apache 2.0 license.
For a copy, see <https://www.apache.org/licenses/LICENSE-2.0.html>.
```

```
Installed Packages
do-agent.x86_64      3.5.2-1      @sonar
```

**Comment by blockloop** [comment]
@exodus4d as mentioned in the issues template, we aren’t able to provide support through GitHub for issues sending metrics, display graphs, errors from the agent, etc. Please reach out to https://cloudsupport.digitalocean.com/s/ so we can provide necessary support.
