### ISSUE TITLE
Where is the configuration?

### ISSUE THREAD

**Issue by pirate** [digitalocean/do-agent#208]
I'd like to change the `noProcesses` config option and bring it down to 2 workers, but I cant find any config file in `/opt/digitalocean` or `/etc` that might be related.

Does `do-agent` have config documentation somewhere that I'm missing?

Thanks!

**Comment by blockloop** [comment]
Hey @pirate there's no configuration file. All of the configuration options are available by calling `do-agent --help`. However, I'm not sure what you mean by "bring it down to 2 workers"

**Comment by pirate** [comment]
Perfect, that works.  Also sorry I mistook the threads for worker processes in tmux because I had coloring off, don't need this option if they're just threads.
