### ISSUE TITLE
error

### ISSUE THREAD

**Issue by cornelius-keino** [digitalocean/do-agent#210]
how can i solve this

 # make fetchindex                                                                                                                        
make: "/etc/make.conf" line 8: Need an operator                                                                                                                                
make: Fatal errors encountered -- cannot continue                                                                                                                              
make: stopped in /usr/home/afnog

**Comment by hoenn** [comment]
@cornelius-keino I'm not sure what you're looking for, but it does look unrelated to the `do-agent`. If you run into an issue with the `do-agent` feel free to open an issue that follows our issue [template](https://github.com/digitalocean/do-agent/blob/master/.github/ISSUE_TEMPLATE.md)
