### ISSUE TITLE
do-agent on CoreOS giving absurd values for Bandwidth

### ISSUE THREAD

**Issue by nunojpg** [digitalocean/do-agent#213]
Statistics before installing agent:

![Screenshot from 2019-11-03 14-55-44](https://user-images.githubusercontent.com/3163870/68086615-e803a280-fe4d-11e9-9e21-31d76da6f8ba.png)

Statistics after installing agent:

![Screenshot from 2019-11-03 15-22-01](https://user-images.githubusercontent.com/3163870/68086617-ee921a00-fe4d-11e9-8c14-22f79fd8dd75.png)

This is for the same instance. I'm running CoreOS stable (2247.5.0) and I start the agent like

docker run --restart always -v /proc:/host/proc:ro -v /sys:/host/sys:ro -d digitalocean/do-agent:stable

**Comment by thorfour** [comment]
Thanks for taking the time to write up an issue. Unfortunately at this time CoreOS is not officially supported by the DO agent, and I wasn't able to reproduce any problems with the agent on the latest version of CoreOS.
