### ISSUE TITLE
[ArchLinux]This script does not support the OS/Distribution on this machine.   

### ISSUE THREAD

**Issue by txl263** [digitalocean/do-agent#214]
#cat /proc/version
`Linux version 4.19.88-1-lts (linux-lts@archlinux) (gcc version 9.2.0 (GCC)) #1 SMP Thu, 05 Dec 2019 12:30:39 +0000`

#curl -sSL https://repos.insights.digitalocean.com/install.sh | sudo bash
```
Cleaning up old sources...OK
Verifying machine compatability...OK
Verifying compatability with script...
This script does not support the OS/Distribution on this machine.
If you feel that this is an error contact support@digitalocean.com
or create an issue at https://github.com/digitalocean/do-agent/issues/new.
```

**Comment by thorfour** [comment]
This is correct behavior. Arch Linux is currently not officially supported.
