### ISSUE TITLE
Improve name of project

### ISSUE THREAD

**Issue by ovikholt** [digitalocean/do-agent#218]
I find myself wondering, "do-agent...? What does it do?" a number of times, while I'm following the upgrade instructions at https://www.digitalocean.com/docs/monitoring/how-to/upgrade-legacy-agent/. Finally I arrive at your github page, and get it.

do-agent is a horrible name! Couldn't you have called it digitalocean-agent????

What's going on with naming these days? Indeed naming always is and remains the most difficult problem in programming, and too many people do it poorly.

**Comment by thorfour** [comment]
Thanks for the input! While I agree it isn't the best name, the decision has been made and we aren't looking to rename at this time.
