### ISSUE TITLE
Build fails on FreeBSD

### ISSUE THREAD

**Issue by blackknight36** [digitalocean/do-agent#22]
Running make build fails on FreeBSD nodes.  Here are the errors shown on my node which is running FreeBSD 10.3.

```
root@bsd1:/usr/src/do-agent # make build
make: "/usr/src/do-agent/Makefile" line 8: Missing dependency operator
make: "/usr/src/do-agent/Makefile" line 10: Need an operator
make: "/usr/src/do-agent/Makefile" line 12: Need an operator
make: "/usr/src/do-agent/Makefile" line 82: Missing dependency operator
make: "/usr/src/do-agent/Makefile" line 83: warning: duplicate script for target "ifeq" ignored
make: "/usr/src/do-agent/Makefile" line 9: warning: using previous script for "ifeq" defined here
make: "/usr/src/do-agent/Makefile" line 83: warning: duplicate script for target "("",)" ignored
make: "/usr/src/do-agent/Makefile" line 9: warning: using previous script for "("",)" defined here
make: "/usr/src/do-agent/Makefile" line 84: Need an operator
make: "/usr/src/do-agent/Makefile" line 86: Need an operator
make: Fatal errors encountered -- cannot continue
make: stopped in /usr/src/do-agent
```

**Comment by geoffgarside** [comment]
Need to use `gmake` rather than `make` as the Makefile uses GNU semantics rather than BSD semantics.

**Comment by blackknight36** [comment]
Thanks, I tried that but the build is still failing after installing the go package.  I also set the GOPATH to /usr/local/go but gmake build claims that it is not set.

root@bsd1:/usr/src/do-agent # set
GOPATH	/usr/local/go

root@bsd1:/usr/src/do-agent # gmake build
>> fetching govendor
package github.com/kardianos/govendor: cannot download, $GOPATH not set. For more details see: go help gopath
gmake: *** [Makefile:21: build] Error 1

**Comment by geoffgarside** [comment]
I found it a bit easier to set the values in my shell properly like below, this seems to fix the `gmake` sub-shells getting the environment variables properly.

``` diff
--- /usr/share/skel/dot.cshrc	2016-10-25 20:28:47.454139000 +0000
+++ .cshrc	2017-02-05 17:26:29.343485000 +0000
@@ -14,13 +14,14 @@

 # These are normally set through /etc/login.conf.  You may override them here
 # if wanted.
-# set path = (/sbin /bin /usr/sbin /usr/bin /usr/local/sbin /usr/local/bin $HOME/bin)
+set path = (/sbin /bin /usr/sbin /usr/bin /usr/local/sbin /usr/local/bin $HOME/bin $HOME/go/bin)
 # setenv	BLOCKSIZE	K
 # A righteous umask
 # umask 22

 setenv	EDITOR	vi
 setenv	PAGER	more
+setenv	GOPATH	$HOME/go

 if ($?prompt) then
 	# An interactive shell -- set some stuff up
```

Then I ran the following

``` shell
mkdir -p $HOME/go/src/github.com/digitalocean
git clone https://github.com/digitalocean/do-agent $HOME/go/src/github.com/digitalocean/
cd $HOME/go/src/github.com/digitalocean/do-agent
gmake build
```

**Comment by blackknight36** [comment]
Thanks, that appears to have fixed the build but unfortunately the agent doesn't actually work.  

017/02/06 15:22:17 Do-Agent version dev
2017/02/06 15:22:17 Do-Agent build master.73b04ed
2017/02/06 15:22:17 Architecture: amd64
2017/02/06 15:22:17 Operating System: freebsd
2017/02/06 15:22:17 Checking for newer version of do-agent
2017/02/06 15:22:17 Unable to update do-agent: Update: Error determining running process: readlink /proc/self/exe: no such file or directory

**Comment by tbartelmess** [comment]
@blackknight36 yeah it looks like the do-agent currently uses procfs to get most of it's data, which is a linux thing. However you can mount a procfs in FreeBSD using https://www.freebsd.org/doc/en/articles/linux-users/procfs.html

**Comment by blackknight36** [comment]
@tbartelmess I mounted /proc but it didn't make any difference.  /proc/self/exe doesn't appear to exist in FreeBSD.

**Comment by geoffgarside** [comment]
It'll likely need implementing in terms of the sysctl interface for FreeBSD support

**Comment by cagedmantis** [comment]
As mentioned above, do-agent relies completely on data collected from the proc pseudo filesystem. It would take a bit of research to find how and where the corresponding metrics are exposed on a vanilla deployment of FreeBSD. It's not currently supported because of this.

**Comment by tbartelmess** [comment]
@cagedmantis let me know if you want a PR for FreeBSD stats. However there are most likly going to be some changes to exsting code since procfs is really central at this point.

**Comment by krzysztofantczak** [comment]
Guys, perhaps switching to this project https://github.com/shirou/gopsutil/ to get stats of VM will help? It works on all major platforms.

**Comment by tbartelmess** [comment]
Any plans for FreeBSD support?

**Comment by SuperDaveAU** [comment]
Sorry to poke an old thread, but I support for FreeBSD on the roadmap?

Having looked at the code it looks like there will need to be several changes to the code to accommodate this, but before doing that I think the project would need to make a decision. 

Is it better making a fork, or would you like do-agent to be used for ALL the droplets that DigitalOcean support including CoreOS and FreeBSD?

**Comment by utlemming** [comment]
@SuperDaveAU We would be more than happy to consider a set of patches to enable FreeBSD. However, switching Linux from ProcFS would probably be a non-starter. If you're willing to do the work, we can have the conversation. 

ALSO, its worth noting that the agent _does_ work on CoreOS and Rancher.  The problem in terms of support is the packaging and distribution of them. I have done some work on container-based solutions (it works :smile:) it hasn't been merged yet. The blocker is really re-working the agent build process so that Containers are automatically emitted and thus supportable. See [1] for more context on how this can be done.

[1] https://github.com/utlemming/do-agent/blob/72eaa205b99f7b10b83672eaf894fb80b919c452/Makefile#L63

**Comment by SuperDaveAU** [comment]
@utlemming, am I correct in thinking that almost all of the metrics are derived from reading values in ProcFS?

**Comment by ekollof** [comment]
man 5 linprocfs, it's part of the Linux compat system inside FreeBSD, but it might make a nice stopgap.

**Comment by AlmightyOatmeal** [comment]
There are Linux compatibility libraries that can be installed that will give you a compatible Linux procfs access:
```
╭─jivanov@irony ~
╰─$ mount
zcool/ROOT/default on / (zfs, local, noatime, nfsv4acls)
devfs on /dev (devfs, local, multilabel)
linprocfs on /compat/linux/proc (linprocfs, local)
linsysfs on /compat/linux/sys (linsysfs, local)
zcool/tmp on /tmp (zfs, local, noatime, nosuid, nfsv4acls)
zcool/storage/docker on /usr/docker (zfs, local, noatime, nfsv4acls)
...
```

So, to enable linprocfs on a FreeBSD host
1) Add this to /etc/rc.conf:
```
linux_enable="YES"
```

2) Add this to /etc/sysctl.conf (well, it's what I'm currently using anyway):
```
compat.linux.osrelease = 2.6.32
```

3) Add this to /etc/make.conf:
```
OVERRIDE_LINUX_BASE_PORT=f8 to /etc/make.conf
```

4) Add this to /etc/fstab:
```
linproc    		/compat/linux/proc  	linprocfs   rw  0   0
# linsys is optional but it may be necessary (I use it)
linsys    		/compat/linux/sys  	linsysfs   rw  0   0
```

5) Create the necessary directories
```
$ sudo mkdir -p /compat/linux/proc
# Optional:
$ sudo mkdir -p /compat/linux/sys
```

6) Mount the filesystem(s):
```
$ sudo mount /compat/linux/proc
# Optional:
$ sudo mount /compat/linux/sys
```

7) Apply the sysctl changes
```
$ sudo sysctl -f /etc/sysctl.conf
```

8) Start the ABI service
```
$ sudo service abi start
```

9) Install a Linux emulator:
```
$ cd /usr/ports/emulators/linux_base-f8
$ sudo make install clean
```

These are the same steps that I use on all of my FreeBSD hosts and I enjoy using htop!

Otherwise FreeBSD does have it's own procfs still, although deprecated, that can be accessed by adding a line into /etc/fstab and then mounting /proc:
```
proc                /proc           procfs  rw,noauto       0       0
```
( https://www.freebsd.org/doc/en_US.ISO8859-1/articles/linux-users/procfs.html )

**Comment by ekollof** [comment]
You don't need the linuxulator to mount the linprocfs. And htop has a native FreeBSD port.

**Comment by blackknight36** [comment]
@AlmightyOatmeal Thanks for the help.  I've verified that the changes listed above work in FreeBSD 10.3 however the go package fails to build due to a missing docker package.

```
root@bsd2:/usr/local/go14/src/github.com/digitalocean/do-agent # gmake
find: illegal option -- t
usage: find [-H | -L | -P] [-EXdsx] [-f path] path ... [expression]
       find [-H | -L | -P] [-EXdsx] -f path [path ...] [expression]
find: illegal option -- t
usage: find [-H | -L | -P] [-EXdsx] [-f path] path ... [expression]
       find [-H | -L | -P] [-EXdsx] -f path [path ...] [expression]
find: illegal option -- t
usage: find [-H | -L | -P] [-EXdsx] [-f path] path ... [expression]
       find [-H | -L | -P] [-EXdsx] -f path [path ...] [expression]

:::::::::::::::: [Tue Dec 18 17:39:48 UTC 2018] target/do-agent-linux-amd64 ::::::::::::::::
docker run --rm -i -u "0" -e "GOOS=linux" -e "GOARCH=amd64" -e "GOPATH=/gopath" -e "GOCACHE=/gopath/src/github.com/digitalocean/do-agent/target/.cache/go" -v "/usr/local/go14/src/github.com/digitalocean/do-agent:/gopath/src/github.com/digitalocean/do-agent" -w "/gopath/src/github.com/digitalocean/do-agent" golang:1.11.2 go build -ldflags ' -X "main.version=1.0.13" -X "main.revision=0d3191e" -X "main.buildDate=Tue Dec 18 17:39:48 UTC 2018" ' -o "target/do-agent-linux-amd64" ./cmd/do-agent
docker: not found
gmake: *** [Makefile:82: target/do-agent-linux-amd64] Error 127
```

At this point I'm not sure it's even worth pursuing this issue.

**Comment by blockloop** [comment]
Unfortunately FreeBSD isn't one of our supported systems, however it might be possible to get a build. You'll notice the BSD version of `find` is also complaining about improper flags because our Makefile is built with GNU semantics. If you tinker with it enough you might be able to produce a binary. It might be easier to run the go build command manually with `go build -ldflags target/do-agent-freebsd ./cmd/do-agent`

**Comment by blockloop** [comment]
That being said, I'm going to close this issue because we don't support FreeBSD at this time.

**Comment by adamwight** [comment]
It would be great if you could point us to documentation about the do-agent communication protocol.  None of the issues above seem like a blocker, but if FreeBSD won't be officially supported then we're probably better off cloning the functionality rather than forking this project.

**Comment by adamwight** [comment]
Would it be possible to set up a different prometheus client to export to DO's sonar?
