### ISSUE TITLE
Usage with kube-rbac-proxy in front of kube-state-metrics

### ISSUE THREAD

**Issue by daurnimator** [digitalocean/do-agent#224]
We use [kube-rbac-proxy](https://github.com/brancz/kube-rbac-proxy) in front of our kube-state-metrics instance as recommended by https://github.com/coreos/kube-prometheus.

How can we configure the do-agent to talk to it? As far as I can see, there is no argument to do-agent to get it to present a valid and RBAC authorized token or client TLS certificate.

Downstream issue: https://github.com/hashbang/gitops/issues/31

**Comment by bsnyder788** [comment]
@daurnimator did you setup your own kubernetes cluster on droplets or are you referring to the managed Kubernetes product (DOKS)?

**Comment by daurnimator** [comment]
> @daurnimator did you setup your own kubernetes cluster on droplets or are you referring to the managed Kubernetes product (DOKS)?

This is with a DOKS cluster.

**Comment by bsnyder788** [comment]
Thanks for the info @daurnimator, I put something on our radar to investigate compatibility and will let you know what I find out.

**Comment by daurnimator** [comment]
.

**Comment by daurnimator** [comment]
wut? why was this closed by the stale bot; there was a comment 11 days ago.

**Comment by bsnyder788** [comment]
no idea why the bot still closed it :/

**Comment by mdanzinger** [comment]
Hey @daurnimator,


v3.9.0 introduces the `bearer-token` and `bearer-token-file` flags allowing you to pass bearer tokens to the agent. You can deploy this version by changing the image tag to "beta" in the do-agent manifest. Please let me know if you encounter any further issues.
