### ISSUE TITLE
do-agent on FreeBSD does build but not run

### ISSUE THREAD

**Issue by mjakob-gh** [digitalocean/do-agent#236]
## Describe the problem
Building the latest version from Github works but running the binary results in the panic below.
```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0xc0 pc=0xbff5cd]

goroutine 1 [running]:
gopkg.in/alecthomas/kingpin%2ev2.(*FlagClause).Default(...)
        /usr/home/freebsd/go/pkg/mod/gopkg.in/alecthomas/kingpin.v2@v2.2.6/flags.go:251
main.init.0()
        /usr/home/freebsd/do-agent/cmd/do-agent/config.go:127 +0x17ad
```

## Steps to reproduce
Install git and golang:
`pkg install git-lite`
`pkg install go`
checkout the code from Github:
`git clone https://github.com/digitalocean/do-agent.git ./do-agent`
cd to do-agent directory:
`cd do-agent`
build agent with command (example, change version, revision and date accordingly):
`go build -ldflags ' -s -w -X "main.version=3.8.0" -X "main.revision=3b03160" -X "main.buildDate=Sun Dec 27 14:53:38 UTC 2020" ' -o ./target/do-agent-freebsd-amd64 ./cmd/do-agent`
run the binary:
`target/do-agent-freebsd-amd64`

## Expected behavior
a running do-agent

## System Information
FreeBSD 12.2-RELEASE-p2

### Local Hack to fix the build
Commenting line 127 in ./do-agent/cmd/do-agent/config.go out 

`//kingpin.CommandLine.GetFlag("collector.diskstats.ignored-devices").Default("^(dm-|ram|loop|fd|(h|s|v|xv)d[a-z]|nvme\\d+n\\d+p)\\d+$")`

results in a (somewhat) working binary:
```
do-agent/./target/do-agent-freebsd-amd64 -v

do-agent (DigitalOcean Agent)

Version:     3.8.0
Revision:    3b03160
Build Date:  So. 27 Dez. 2020 15:05:38 UTC
Go Version:  go1.15.6
Website:     https://github.com/digitalocean/do-agent

Copyright (c) 2020 DigitalOcean, Inc. All rights reserved.

This work is licensed under the terms of the Apache 2.0 license.
For a copy, see <https://www.apache.org/licenses/LICENSE-2.0.html>.
```

I suspect the relevant line is linux specific and should go in the into this file config_linux.go

**Comment by bsnyder788** [comment]
This should be resolved now @mjakob-gh with the latest commit to master. Please re-open if you are still seeing issues.

**Comment by mjakob-gh** [comment]
With this commit, do-agent now builds and runs without error on FreeBSD. Values for "CPU", "Load", "Disk Usage" and "Bandwidth" are updated on the graph page. Looking forward to the "Memory" and "Disk I/O" graphs appearing, too :wink:

**Comment by hughcrt** [comment]
Any update about "Memory" and "Disk I/O" for FreeBSD?
