### ISSUE TITLE
Agent incorrectly calculates memory usage

### ISSUE THREAD

**Issue by computator** [digitalocean/do-agent#245]
## Describe the problem
The agent uses an outdated/inaccurate method to calculate memory usage percentage. This results in getting high memory usage alerts when there is actually plenty of memory, as well as inaccurate usage metrics.

Here's a specific example of a node where I just did something that scanned a lot of files and thus the kernel cached the files in unused memory (which is of course reclaimable). The agent reports my memory usage at 86%, but the actual usage is much lower at 41%:
```
# free -m
              total        used        free      shared  buff/cache   available
Mem:            991         113          65          56         813         588
Swap:             0           0           0
```

Here are three other places with more information where people have reported the same issue:
https://ideas.digitalocean.com/ideas/CPX-I-17
https://www.digitalocean.com/community/questions/digitalocean-is-calculating-wrong-the-memory-graph-in-monitoring
https://www.digitalocean.com/community/questions/graphs-and-monitoring-differs-from-real-memory-usage-2

## System Information
Distribution and version:
CentOS Linux release 7.5.1804 (Core) 

### do-agent information:
`/opt/digitalocean/bin/do-agent --version`:
```
do-agent (DigitalOcean Agent)

Version:     3.9.4
Revision:    766c949
Build Date:  Fri Mar 12 20:37:53 UTC 2021
Go Version:  go1.16.2
Website:     https://github.com/digitalocean/do-agent
```
`yum --cacheonly list do-agent`:
```
do-agent.x86_64                    3.9.4-1                 @digitalocean-agent
```

**Comment by bsnyder788** [comment]
Thanks for the report @computator, we will definitely assess this and get back to you.

**Comment by bsnyder788** [comment]
:wave: hey @computator I added support to collect MemAvailable in the lastest agent build (3.10.0 - currently in beta). Will probably move that to the stable release channel early next week. After that I will be working on updating to use the (MemTotal - MemAvailable) / MemTotal for machines that have MemAvailable available (Linux 3.14+ I believe).

**Comment by computator** [comment]
Awesome! Glad to hear it!

**Comment by bsnyder788** [comment]
@computator  the graphs in the UI should now use the (MemTotal - MemAvailable) / MemTotal calculation if you have the 3.10.0 agent installed. Would you mind checking it out and report back if things are looking better for you?  We have not migrated the alerts to use this new calculation yet, but will be soon if no regressions are detected. Thanks!

**Comment by computator** [comment]
@bsnyder788 Everything seems to be working correctly as far as I can tell!

**Comment by bsnyder788** [comment]
@computator All the existing alert policies have been migrated to the new formula as well. Going to close this issue out. Thanks again for the report!
