### ISSUE TITLE
Agent install.sh fails on Centos 6

### ISSUE THREAD

**Issue by enlyt** [digitalocean/do-agent#33]
I wasn't really sure where to post this issue, as it relates to the script hosted on the following:
`curl -sSL https://agent.digitalocean.com/install.sh | sh`

Hopefully you guys can find the proper home for it.

The following line in the install.sh script fails on my platform, as the output for the following yields two results:
`rpm -q --whatprovides redhat-release --queryformat "%{VERSION}\n" | sed 's/\/.*//' | sed 's/\..*//'                                                                                                                    | sed 's/Server*//'`

The reason for the two results is the following:
```
[root@sb1 ~]# rpm -q --whatprovides redhat-release
centos-release-6-7.el6.centos.12.3.x86_64
centos-release-6-8.el6.centos.12.3.x86_64
```

Making the following change I was able to get the script to work properly:
`rpm -q --whatprovides redhat-release --queryformat "%{VERSION}\n" |` **tail -n 1 |** `sed 's/\/.*//' | sed 's/\..*//' | sed 's/Server*//'`

**Comment by utlemming** [comment]
taking a look....
