### ISSUE TITLE
do-agent cannot be installed on Debian with sysvinit (apparently)

### ISSUE THREAD

**Issue by kolargol** [digitalocean/do-agent#35]
Latest 0.4.11, apt install fails with:

```
Preparing to unpack .../do-agent_0.4.11_amd64.deb ...
do-agent: unrecognized service
Unpacking do-agent (0.4.11) ...
Setting up do-agent (0.4.11) ...
do-agent: unrecognized service
dpkg: error processing package do-agent (--configure):
 subprocess installed post-installation script returned error exit status 1
Errors were encountered while processing:
 do-agent
E: Sub-process /usr/bin/dpkg returned an error code (1)
```

this is on Debain with systemd removed and running under SysV

**Comment by yaazkal** [comment]
Hi I get the same error on version 0.5.1.
Debian 8.10
sysvinit

Is there plans to support it?

```
# curl -sSL https://agent.digitalocean.com/install.sh | sh
Detected Debian GNU/Linux 8 (jessie)...installing the DigitalOcean Agent
Reading package lists... Done
Building dependency tree
Reading state information... Done
apt-transport-https is already the newest version.
curl is already the newest version.
0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  1760  100  1760    0     0   103k      0 --:--:-- --:--:-- --:--:--  107k
OK
Reading package lists... Done
Building dependency tree
Reading state information... Done
The following NEW packages will be installed:
  do-agent
0 upgraded, 1 newly installed, 0 to remove and 0 not upgraded.
Need to get 2622 kB of archives.
After this operation, 7840 kB of additional disk space will be used.
Get:1 https://repos.sonar.digitalocean.com/apt/ main/main do-agent amd64 0.5.1 [2622 kB]
Fetched 2622 kB in 0s (11.1 MB/s)
Selecting previously unselected package do-agent.
(Reading database ... 61044 files and directories currently installed.)
Preparing to unpack .../do-agent_0.5.1_amd64.deb ...
Unpacking do-agent (0.5.1) ...
Setting up do-agent (0.5.1) ...
do-agent: unrecognized service
dpkg: error processing package do-agent (--configure):
 subprocess installed post-installation script returned error exit status 1
Errors were encountered while processing:
 do-agent
E: Sub-process /usr/bin/dpkg returned an error code (1)
```

**Comment by aacunaa** [comment]
Hello, the same error but with systemd

`sh /tmp/install.sh 
Detected Debian GNU/Linux 8 (jessie)...installing the DigitalOcean Agent
Reading package lists... Done
Building dependency tree       
Reading state information... Done
apt-transport-https is already the newest version.
curl is already the newest version.
0 upgraded, 0 newly installed, 0 to remove and 92 not upgraded.
1 not fully installed or removed.
After this operation, 0 B of additional disk space will be used.
Setting up do-agent (0.5.1) ...
Failed to get D-Bus connection: Unknown error -1
dpkg: error processing package do-agent (--configure):
 subprocess installed post-installation script returned error exit status 1
Errors were encountered while processing:
 do-agent
E: Sub-process /usr/bin/dpkg returned an error code (1)
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  1760  100  1760    0     0   112k      0 --:--:-- --:--:-- --:--:--  114k
OK
Reading package lists... Done
Building dependency tree       
Reading state information... Done
do-agent is already the newest version.
0 upgraded, 0 newly installed, 0 to remove and 92 not upgraded.
1 not fully installed or removed.
After this operation, 0 B of additional disk space will be used.
Setting up do-agent (0.5.1) ...
Failed to get D-Bus connection: Unknown error -1
dpkg: error processing package do-agent (--configure):
 subprocess installed post-installation script returned error exit status 1
Errors were encountered while processing:
 do-agent
E: Sub-process /usr/bin/dpkg returned an error code (1)`

**Comment by Gesias** [comment]
I have the same issue, any update?

**Comment by rpscs** [comment]
Unable to install on Debian 9.9 and SysV

```
Setting up do-agent (2.2.0) ...
Detecting SELinux
SELinux not enforced
Unknown init system. Exiting...
dpkg: error processing package do-agent (--configure):
 subprocess installed post-installation script returned error exit status 1
Errors were encountered while processing:
 do-agent
E: Sub-process /usr/bin/dpkg returned an error code (1)
```
Any update, issue has not been resolved.

**Comment by Pls** [comment]
Same problem on Debian 9.7, maby anyone has workaround on this issue?
