### ISSUE TITLE
New graphs not showing up

### ISSUE THREAD

**Issue by amejiarosario** [digitalocean/do-agent#47]
I installed the agent using `curl -sSL https://agent.digitalocean.com/install.sh | sh` on a Ubuntu 16 machine. Two days later and I still don't see the new graphs like disk usage and memory in the DO dashboard. Is there any way to debug it/logs?

**Comment by gjsman** [comment]
I am having the same problem. ???

**Comment by amejiarosario** [comment]
After some time they started showing up... closing
