### ISSUE TITLE
tufLocalStore is not being created

### ISSUE THREAD

**Issue by kicco** [digitalocean/do-agent#48]
Hi I'm experiencing issues when i try to start do-agent: 
`2017/09/08 15:41:28 Unable to read credentials: DigitalOcean sonar service returned unexpected status: 401`

tufLocalStore file is not being created, tried to update/re-install...

**Comment by pehbehbeh** [comment]
Same issue here. Have you found out anything?

**Comment by NicholasPCole** [comment]
Have either of you opened a ticket for our support team on this (and have a ticket number that you wouldn't mind sharing here)? It may be a Droplet-level issue that our engineers can run a fix for on the underlying hypervisor, but it'd be good to have the report internally too so we have a good idea how many customers are affected.

**Comment by pehbehbeh** [comment]
Yes, I did: 689653

**Comment by YossiAharon** [comment]
I also have the same issue and opened a ticket (#677637) but this issue not solved yet even after they migrated my droplet to another hypervisor.

**Comment by kicco** [comment]
Yup I opened ticket #587327 and a couple of others while I was digging up the issue.

Running `systemctl status do-agent` it shows sonar returning 401s. I tried purge do and reinstall, force v0.5.0 but no dice. I `touched` the file in `/run/digitalocean-agent` but no dice either, ended up rebuilding the droplet.
