### ISSUE TITLE
Script install.sh adds the wrong baseurl in RPM repo file /etc/yum.repos.d/digitalocean-agent.repo

### ISSUE THREAD

**Issue by sigmundv** [digitalocean/do-agent#49]
The install instructions for `do-agent` tell me to run the command `curl -sSL https://agent.digitalocean.com/install.sh | sh`, but doing that fails on my Fedora 26 droplet. The script `install.sh` adds a repo called `digitalocean-agent` by writing a file `/etc/yum.repos.d/digitalocean-agent.repo` like this

```
$ cat /etc/yum.repos.d/digitalocean-agent.repo 
[digitalocean-agent]
name=DigitalOcean agent
baseurl=https://repos.sonar.digitalocean.com/yum/\$basearch
failovermethod=priority
enabled=1
gpgcheck=1
gpgkey=https://repos.sonar.digitalocean.com/sonar-agent.asc
```
The reason this repo doesn't work is that `\$basearch` leads to an invalid `baseurl`. The correct is `$basearch`, and when I delete the backslash `do-agent` installs successfully.

Can you please correct the `install.sh` script? The issue is the _heredoc_ block from line 48 to line 58. Line 48 reads `cat > /etc/yum.repos.d/digitalocean-agent.repo <<"EOM"`, but the quotes around `EOM` mean that the `\$` on line 51 is not treated as an escape sequence, but repeated verbatim, hence we get the repo file as listed above. If you remove the quotes around `EOM` the `$` is escaped correcltly and we get the correct `baseurl` in the repo file. Alternatively you can keep the quotes around `EOM on line 48`, but then you don't need to escape `$`.

Thank you in advance

**Comment by utlemming** [comment]
Thanks, and its now fixed.
