### ISSUE TITLE
FR: RancherOS

### ISSUE THREAD

**Issue by BeatriceFendt** [digitalocean/do-agent#51]
It would be great to use the do-agent on RancherOS 👌

**Comment by mcm-ham** [comment]
The readme mentions how to build the agent in a docker container and run it which works in rancheros. However, I had to make this fix first: https://github.com/digitalocean/do-agent/issues/54

**Comment by mcm-ham** [comment]
Thanks JayAndCatchFire, this issue is now fixed and can be closed.
