### ISSUE TITLE
docker image missing

### ISSUE THREAD

**Issue by CanRau** [digitalocean/do-agent#59]
Good sunday morning :)
Just tried pulling the image on a new CoreOS doplet but it doesn't seem to exist anymore the [hub](https://hub.docker.com/_/do-agent/) page shows 404 and docker pull isn't able to access either

What a pity :/
Anything I missed?

**Comment by normaclyde** [comment]
DigitalOcean person here.  Sorry for the delay.  We're in the process of rolling out a new metrics agent, which is now in private beta.  It's based off of Prometheus [node_exporter](https://github.com/prometheus/node_exporter), so will be easier to plug in new metrics scrapers in the future.

If you would like to try it out the instructions are in the repo [here](https://github.com/digitalocean/metrics-agent).  I've confirmed that the Docker pull [is available](https://hub.docker.com/r/digitalocean/metrics-agent/) for the agent.

**Comment by klamontagne** [comment]
Hello! the readme now says to pull [digitalocean/do-agent](https://hub.docker.com/r/digitalocean/do-agent). It seems to have been changed among #66

**Comment by CanRau** [comment]
Great 🎉  than I'll close this issue?!
