### ISSUE TITLE
Build fails on Arch Linux

### ISSUE THREAD

**Issue by ImNtReal** [digitalocean/do-agent#6]
When I try to build on Arch, the govendor sync step fails with:
Error: Package "/home/imntreal/do-agent/src/do-agent-0.4.5" not a go package or not in GOPATH.

Setting $GOPATH to "/home/imntreal/do-agent/src" doesn't help.

**Comment by ankur-jain** [comment]
We currently do not support Arch Linux. 
As we expand the support of our agent, we may include Arch Linux support. Currently we support only following Linux distributions: Ubuntu, CentOS and Debian.

**Comment by ImNtReal** [comment]
I got the same thing when I simply downloaded the tarball, extracted it, and ran make build on CentOS.

**Comment by alzeih** [comment]
I don't get an error here in Arch when this repository is cloned to path

`$GOPATH/src/github.com/digitalocean/do-agent`  

See Notes in https://github.com/kardianos/govendor/blob/master/README.md and https://wiki.archlinux.org/index.php/Go#.24GOPATH

**Comment by Nefari0uss** [comment]
@ImNtReal Did you ever get this working? I've tried to use the AUR package which installs just fine but not sure what I need to do to enable graphs.

**Comment by alzeih** [comment]
@Nefari0uss to run it just (as root) `systemctl enable --now do-agent.service`. 

I also added https://aur.archlinux.org/packages/do-agent-git/ to the AUR if you want the git version for some reason.

**Comment by Nefari0uss** [comment]
Ah. Should have realized that it's a service. I'll give it a go. Thanks @alzeih!
