### ISSUE TITLE
Update: Error initializing repository: tuf: missing remote metadata root.json

### ISSUE THREAD

**Issue by chapinb** [digitalocean/do-agent#74]
Before opening an issue, make sure there is not a similar issue [already open](https://github.com/digitalocean/do-agent/issues)

* Appears related to #43 

## Describe the problem

Error in logs `Unable to update do-agent: Update: Error initializing repository: tuf: missing remote metadata root.json`

## Steps to reproduce

Though this message appears nearly-hourly, it is also generated when running:

```
root@system:/opt/digitalocean/bin# ./do-agent 
2019/01/17 01:41:37 Do-Agent version 0.5.1
2019/01/17 01:41:37 Do-Agent build HEAD.c799b1e
2019/01/17 01:41:37 Architecture: amd64
2019/01/17 01:41:37 Operating System: linux
2019/01/17 01:41:37 Checking for newer version of do-agent
2019/01/17 01:41:37 Unable to update do-agent: Update: Error initializing repository: tuf: missing remote metadata root.json
root@system:/opt/digitalocean/bin# ./do-agent -force_update
2019/01/17 01:46:35 Do-Agent version 0.5.1
2019/01/17 01:46:35 Do-Agent build HEAD.c799b1e
2019/01/17 01:46:35 Architecture: amd64
2019/01/17 01:46:35 Operating System: linux
2019/01/17 01:46:35 Checking for newer version of do-agent
2019/01/17 01:46:35 Unable to update do-agent: Update: Error initializing repository: tuf: missing remote metadata root.json
```

## Expected behavior

Updating? Unsure, I haven't done anything manual to date.

## System Information
Distribution: Ubuntu 16.04

Version: 0.51

Metrics-Agent Version: (unsure how to confirm)

(paste the output of `do-agent --version`)

```
root@system:/opt/digitalocean/bin# ./do-agent --version
flag provided but not defined: -version
Usage of ./do-agent:
  -force_update
    	Update the version of do-agent.
  -log_level string
    	Log level to log: ERROR, INFO, DEBUG (default "INFO")
  -log_syslog
    	Log to syslog.
```

**Comment by saharben** [comment]
Same issue on CentOS Linux 7.6.1810.
Kernel version: Linux 3.10.0-957.1.3.el7.x86_64.

./do-agent -force_update
2019/01/17 13:37:24 Do-Agent version 0.5.1
2019/01/17 13:37:24 Do-Agent build HEAD.c799b1e
2019/01/17 13:37:24 Architecture: amd64
2019/01/17 13:37:24 Operating System: linux
2019/01/17 13:37:24 Checking for newer version of do-agent
2019/01/17 13:37:24 Unable to update do-agent: Update: Error initializing repository: tuf: missing remote metadata root.json

**Comment by blockloop** [comment]
Yesterday we removed the tuf metadata from our repositories and are no longer supporting it. Although the agent makes noise, it should continue to operate normally. We will be pushing an officially updated version of the agent with the tuf code removed in the coming weeks. The new version of the do-agent will use standard Linux package managers for updating.

**Comment by rickmacgillis** [comment]
@blockloop - So we can expect log bloat which clouds our alerts for weeks? That could pose a security risk if we don't look through the list thoroughly enough when real problems are in the list.

Any chance you can find a solution to mask this error if it's a false positive?

**Comment by thorfour** [comment]
@rickmacgillis We're looking into copying over the tuf metadata as a stopgap to suppress any errors.

**Comment by blockloop** [comment]
We've pushed a fix earlier today. You should no longer see the issue. Sorry about that!
