### ISSUE TITLE
Repo name change main -> beta

### ISSUE THREAD

**Issue by rickmacgillis** [digitalocean/do-agent#75]
Before opening an issue, make sure there is not a similar issue [already open](https://github.com/digitalocean/do-agent/issues)
- Doesn't seem to be an existing issue

## Describe the problem
When I manually ran `sudo apt-get update` to update the list of repos, I saw the following items.
```
...
N: Repository 'https://repos.sonar.digitalocean.com/apt main InRelease' changed its 'Version' value from '' to '1.0'
E: Repository 'https://repos.sonar.digitalocean.com/apt main InRelease' changed its 'Codename' value from 'main' to 'beta'
N: This must be accepted explicitly before updates for this repository can be applied. See apt-secure(8) manpage for details.
```
As `main` insinuates it's for general releases IMO, it sounds like the general release channel got repurposed to a beta release channel. However, despite the obvious repercussions of this bad practice, I have no idea where I can point our production servers so we once again have a stable channel.

## Steps to reproduce
In Ubuntu (or presumably any Debian-based system), follow the README.md file's infructions in this repo. Below is what it says at the time of writing.

```
echo "deb https://repos.sonar.digitalocean.com/apt main main" > /etc/apt/sources.list.d/sonar.list
curl https://repos.sonar.digitalocean.com/sonar-agent.asc | sudo apt-key add -
sudo apt-get update
```
As this says it was changed, then things will most likely go smoothly and not show any issues. However, if you examine the [metadata for the repository](https://repos.sonar.digitalocean.com/apt/dists/main/InRelease), you'll see that the file contains the following information at the top. (FYI: `main main` apparently points to `main InRelease` which causes this issue.)

```
-----BEGIN PGP SIGNED MESSAGE-----
Hash: SHA512

Architectures: amd64 i386
Codename: beta
Components: main contrib non-free
Date: Mon, 14 Jan 2019 22:38:32 +0000
Label: . main
Origin: . main
Suite: main
Version: 1.0
...
```

## Expected behavior
Have `main main` be the stable repository, and exclusively use `beta main` for the beta channel.

## System Information
Distribution: 
```
$ cat /etc/os-release
NAME="Ubuntu"
VERSION="18.04.1 LTS (Bionic Beaver)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 18.04.1 LTS"
VERSION_ID="18.04"
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
VERSION_CODENAME=bionic
UBUNTU_CODENAME=bionic
```

Version:
N/A

Metrics-Agent Version:
N/A

(paste the output of `do-agent --version`)
N/A

**Comment by blockloop** [comment]
Okay we've pushed a fix for now
